NAME 							VALUE
LOCAL_INSTALLERS_PATH 			C:\Temp\Automation
SQL_SERVER_2014_INSTALLPATH		C:\Program Files (x86)\Microsoft SQL Server
FILESHARE_PASSWORD
FILESHARE_SQLSERVER				SQLServer
PATHTOSOURCE
FILESHARE
FILESHARE_USERNAME
FILE_SERVER
SQLSVCPASSWORD					 vmware1!
SQLSYSADMINACCOUNTS				.\Administrator
SQLSVCACCOUNT					.\Administrator

AGTSVCPASSWORD					vmware1!
ISSVCPASSWORD					vmware1!
SAPWD							vmware1!
INSTANCEDIR						C:\Program Files\Microsoft SQL Server




$SQL_SERVER_2014_INSTALLPATH="C:\Program Files (x86)\Microsoft SQL Server"
$FILESHARE_PASSWORD="vmware1!"
$FILESHARE_USERNAME="admin"
$FILESHARE="192.168.1.250"
$LOCAL_INSTALLERS_PATH ="C:\Temp\Automation"
$FILESHARE_SQLSERVER="SQLServer"
$FILESHARE="\\192.168.1.251\ViewNAS\SQL2016\Setup"
$FILESHARE_USERNAME="admin"
$FILE_SERVER="192.168.1.251"
$SQLSVCPASSWORD="vmware1!"
$SQLSYSADMINACCOUNTS=".\Administrator"
$SQLSVCACCOUNT=".\Administrator"
$AGTSVCPASSWORD	="vmware1!"
$ISSVCPASSWORD="vmware1!"
$SAPWD	="vmware1!"
$INSTANCEDIR="C:\Program Files\Microsoft SQL Server"








$DebugPreference = "Continue"

#verify network connectivity to file server..........
Test-Connection -ComputerName  $FILE_SERVER

#copy from share repository
net use $FILESHARE /user:$FILESHARE_USERNAME $FILESHARE_PASSWORD




#Copy installer binaries locally from share
Copy-Item -Path $FILESHARE  -Destination  $LOCAL_INSTALLERS_PATH –Recurse

#Set SQL Server 2016 silent installer command-line arguments and installation
try { 
	  C:\Temp\Automation\SQL_Server_2016\setup.exe /IACCEPTSQLSERVERLICENSETERMS='True' /ACTION='Install' /ENU='True' /QUIET='True' /QUIETSIMPLE='False' /UpdateEnabled='True' /FEATURES='SQLENGINE' /UpdateSource='MU' /HELP='False' /INDICATEPROGRESS='False' /X86='False' /INSTALLSHAREDDIR=$INSTANCEDIR /INSTALLSHAREDWOWDIR='$SQL_SERVER_2014_INSTALLPATH' /INSTANCENAME='MSSQLSERVER' /INSTANCEID='MSSQLSERVER' /SQMREPORTING='True' /ERRORREPORTING='False' /RSINSTALLMODE='DefaultNativeMode' /ERRORREPORTING='True' /INSTANCEDIR=$INSTANCEDIR /AGTSVCACCOUNT='NT Service\SQLSERVERAGENT' /AGTSVCSTARTUPTYPE='Manual' /COMMFABRICPORT='0' /COMMFABRICNETWORKLEVEL='0' /COMMFABRICENCRYPTION='0' /MATRIXCMBRICKCOMMPORT='0' /SQLSVCSTARTUPTYPE='Automatic' /FILESTREAMLEVEL='0' /ENABLERANU='False' /SQLCOLLATION='SQL_Latin1_General_CP1_CI_AS' /SQLSVCACCOUNT='NT AUTHORITY\SYSTEM' /SQLSYSADMINACCOUNTS=$SQLSYSADMINACCOUNTS /SQLBACKUPDIR='C:\SQLBCK' /SQLUSERDBDIR='C:\SQLDB' /SQLUSERDBLOGDIR='C:\SQLLOG' /SQLTEMPDBDIR='C:\SQLTMP' /ADDCURRENTUSERASSQLADMIN='False' /TCPENABLED='1' /NPENABLED='0' /BROWSERSVCSTARTUPTYPE='Disabled' /RSSVCACCOUNT='NT AUTHORITY\SYSTEM' /RSSVCSTARTUPTYPE='Automatic' /SQLSVCPASSWORD=$SQLSVCPASSWORD /AGTSVCPASSWORD=$AGTSVCPASSWORD /ISSVCPASSWORD=$ISSVCPASSWORD /SAPWD=$SAPWD;
	  C:\Temp\Automation\SQL_Server_Management_Studio\SSMS-Setup-ENU.exe /install /quiet /norestart; 
	  exit 0; 
	
} catch { 
	exit 1; 
}
